GET http://localhost:5000/users
Authorization: Bearer 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Abiyu",
    "email": "email@gmail.com",
    "password": "1234",
    "confPassword": "1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "1234"
}

###
GEt http://localhost:5000/token

###
DELETE http://localhost:5000/logout